### ISSUE TITLE
User Story 1 - List of proposed goals

### ISSUE THREAD

**Issue by AliaksandraNovikava** [AliaksandraNovikava/AimHigh#1]
## Value proposition

As an user
I want to see a list of proposed goals
So that I have inspirations for my personal development.

## Description

<img src="https://user-images.githubusercontent.com/132850354/251106885-f86e5d0b-d8bb-48a5-a70c-19510c1b4ff6.jpeg" width="300">

## Acceptance criteria

- [ ] A headline "Choose goal" is displayed 
- [ ] Previews of all proposed goals are displayed as a list
- [ ] A goal's title is displayed in each preview
- [ ] A goal's icon is displayed in each preview

## Tasks

- [ ] Create `const goals` with an array of proposed goals
- [ ] Create the component `ProposedGoalPreview` to render a preview of a proposed goal
- [ ] Style the preview
- [ ] Create the component `ProposedGoalsList` to render a list of all previews
- [ ] Style the list

**Comment by DErdmann1** [comment]
Good one :)
