### ISSUE TITLE
User Story 6 - My goals details view

### ISSUE THREAD

**Issue by AliaksandraNovikava** [AliaksandraNovikava/AimHigh#10]
## Value proposition

As an user
I want to see a details view of my set goals
So that I have a better understanding of each goal's specific parameters, such as intervals or deadlines.

## Description

<img src="https://user-images.githubusercontent.com/132850354/252996979-c42cb6eb-fda0-431e-b8b2-ece3ddcce246.jpeg" width="450">

## Acceptance criteria

- [ ] Clicking on a goal preview opens a goals details view
- [ ] A close-button is displayed on the goals details view
- [ ] An icon is displayed 
- [ ] A headline is displayed
- [ ] If repetition was set, targetPerInterval is displayed
- [ ] If repetition was set, interval is displayed
- [ ] If repetition was set, a DayPicker is displayed
- [ ] If deadline was set, a deadline is displayed

## Tasks

- [ ] Add React DayPicker to my dependencies
- [ ] Create the component `NewGoalDetails`
- [ ] Specify conditions when which field should be rendered

**Comment by JivanaLipsewers** [comment]
Nice wireframes! Your user story lgtm :)
