### ISSUE TITLE
User Story 7 - Delete a set goal

### ISSUE THREAD

**Issue by AliaksandraNovikava** [AliaksandraNovikava/AimHigh#11]
## Value proposition

As an user
I want to be able to delete a set goal
So that I can adjust my goal list as needed and maintain a clear overview.

## Description

<img src="https://user-images.githubusercontent.com/132850354/253211778-7b34b81e-274d-4293-90a3-d28f879bc700.jpeg" width="300">

## Acceptance criteria

- [ ] A "Delete" button is displayed on the goals details view
- [ ] Clicking on the "Delete" button deletes the goal from "My goals" list

## Tasks

- [ ] Add button to the component `NewGoalDetails`
- [ ] Add  a handler function

**Comment by tejue** [comment]
Hey Alex, looks fine to me :) small and light. Nothing to add :)
