### ISSUE TITLE
User Story 8 - Edit set goal

### ISSUE THREAD

**Issue by AliaksandraNovikava** [AliaksandraNovikava/AimHigh#12]
## Value proposition

As an user
I want to be able to edit a set goal
So that I can optimize my goal-setting process by adapting set goals based on new circumstances.

## Description

<img src="https://user-images.githubusercontent.com/132850354/253194863-0a557162-60a8-4cbb-9b7b-1de7feff900b.jpeg" width="450">

## Acceptance criteria

- [ ] An "Edit" button is displayed on the goals details view
- [ ] Clicking on the "Edit" button replaces it and the "Delete" button with "Save" and "Cancel" buttons and opens 3 input fields to set new parameters
- [ ] Clicking on the "Save" button saves the edited goal
- [ ] Clicking on the "Cancel" button makes you go out of the edit mode

## Tasks

- [ ] Add new buttons to the component `NewGoalDetails`
- [ ] Add input fields to the component `NewGoalDetails`
- [ ] Add handler functions

**Comment by tejue** [comment]
As US 7, looks good :) I was wondering how you get in and out of the goal but I suppose this is another US

**Comment by AliaksandraNovikava** [comment]
Hey @tejue . Thanks for your review☀️
You're right. This topic is covered in my [User Story 6 - My goals details view](https://github.com/AliaksandraNovikava/capstone-alex/issues/10) .
