### ISSUE TITLE
User Story 9 - Statistics

### ISSUE THREAD

**Issue by AliaksandraNovikava** [AliaksandraNovikava/AimHigh#17]
## Value proposition

As an user
I want to have statistics of my achievements
So that I can track my progress, analyze my performance and adjust my goals if necessary.

## Description

<img src="https://user-images.githubusercontent.com/132850354/254652728-2674f0b2-fc97-40f5-9e01-cdb578fe410f.jpeg" width="300">

## Acceptance criteria

- [ ] A navigation link labeled "Statistics" is displayed
- [ ] Clicking the "Statistics" shows the statistics page
- [ ] A headline "Statistics" is displayed
- [ ] Statistics of "goals in progress" and "goals completed" are displayed
- [ ] A headline "My progress" is displayed
- [ ] Active goals that have a set repetition are displayed as a list
- [ ] Each goal has a number of days marked in the calendar (on the goals details view) displayed

## Tasks

- [ ] Create the page `pages/statistics/index` 
- [ ] Add navigation link for the statistics page
- [ ] Create the component `SetGoalsStatistics`
- [ ] Create the component `ActiveGoalsProgress`
- [ ] Style the components

**Comment by FlorianNova** [comment]
Looks good to me! 🙂 👍
