### ISSUE TITLE
User Story 10 - List of all set deadlines

### ISSUE THREAD

**Issue by AliaksandraNovikava** [AliaksandraNovikava/AimHigh#18]
## Value proposition

As an user
I want to have a list of all set deadlines
So that I have a clearer overview and can prioritize my goals accordingly.

## Description

<img src="https://user-images.githubusercontent.com/132850354/254675411-47da48e7-5ce5-40ac-bf65-cddd91d2314a.jpeg" width="300">

## Acceptance criteria

- [ ] Tabs labeled "My progress" and "Deadlines" are displayed
- [ ] Clicking on "Deadlines" switches the tab content
- [ ] A list of goals with set deadline is displayed
- [ ] Each goal shows the remaining days until the deadline

## Tasks

- [ ] Create tabs for "My progress" and "Deadlines"
- [ ] Write a logic to calculate the remaining days until the deadline
- [ ] Style the tabs

**Comment by oliverhees** [comment]
Great Job! This looks good for me :)
