### ISSUE TITLE
User Story 11 - Tracking repetition

### ISSUE THREAD

**Issue by AliaksandraNovikava** [AliaksandraNovikava/AimHigh#19]
## Value proposition

As an user
I want to track the set repetition
So that I can see how well I'm meeting my target and track my improvement or consistency.

## Description

<img src="https://user-images.githubusercontent.com/132850354/254686047-3abe017a-3da6-4e71-8271-56d7a92eb8ac.jpeg" width="450">

## Acceptance criteria

- [ ] Each goal in "My progress" list is highlighted differently according to whether the set repetition was achieved or not
- [ ] Clicking on a goal shows a message stating whether the set repetition was achieved or not

## Tasks

- [ ] Write logic that compares a goals set repetition with its marked days on the DayPicker
- [ ] Style the goals according to whether the set repetition was achieved or not

**Comment by StrongCurrent** [comment]
i can understand everything. looks great 👍
