### ISSUE TITLE
User Story 2 - Form to set a goal

### ISSUE THREAD

**Issue by AliaksandraNovikava** [AliaksandraNovikava/AimHigh#2]
## Value proposition

As an user
I want a form in two versions to set a goal
So that I can specify measurable criteria for each goal to create a roadmap for my personal development journey.

## Description

<img src="https://user-images.githubusercontent.com/132850354/251171416-18ae2871-13ce-4a94-bdb0-28ba7a06de11.jpeg" width="600">

## Acceptance criteria

- [ ] A button "Set your own goal" is displayed
- [ ] Clicking on a goal preview shows form A in a modal
- [ ] Clicking on the button "Set your own goal" shows form B in a modal
- [ ] An icon is displayed in each form
- [ ] Each form has a headline
- [ ] Form B has an input field to define the new goal
- [ ] Form A has a counter
- [ ] Form A has a dropdown menu to choose an interval
- [ ] Form B has a checkbox to set repetition
- [ ] If the checkbox to set repetition is checked from B displays a counter and a dropdown menu to choose an interval
- [ ] Each form has a checkbox to set a deadline
- [ ] If the checkbox to set a deadline is checked an input field to set a deadline date is displayed
- [ ] Each form has a button "Add your goal" 

## Tasks

- [ ] Create the component `NewGoalForm`
- [ ] Create the component `Button`
- [ ] Create modal for the form
- [ ] Specify conditions when version A or version B should be rendered
- [ ] Style modal
- [ ] Write a function to create a new goal entry

**Comment by vaupunkt** [comment]
It looks good and is very detailed. at first i thought, that this should be two US, but i understand that you want to use one component to display both, so i think it is ok to do it in one User Story :)

**Comment by AliaksandraNovikava** [comment]
At first I wanted to make two different forms. But as you can see they are so similar, so I decided to combine them in one form. I hope my code won't be to complicated😅
