### ISSUE TITLE
User Story 12 - Header with a greeting and a short app description

### ISSUE THREAD

**Issue by AliaksandraNovikava** [AliaksandraNovikava/AimHigh#23]
## Value proposition

As an user
I want to have a header with a personalized greeting and a short app description
So that I have a more user-centric and welcoming experience and can also learn more about the app I'm using.

## Description

<img src="https://user-images.githubusercontent.com/132850354/256572002-a3ee0366-99f2-4871-803d-99a47f1dd048.jpeg" width="600">

## Acceptance criteria

- [ ] A header with a greeting is displayed
- [ ] Clicking on the greeting opens a modal with the greeting and additional info about the app
- [ ] An edit button is displayed
- [ ] Clicking on the edit button switches to edit mode where the name in the greeting can be edited
- [ ] In edit mode a save button is displayed
- [ ] Clicking on the save buttons saves the new name in the greeting 

## Tasks

- [ ] Create the component `Header`
- [ ] Write a logic for the Header to be edited
- [ ] Style the `Header`
- [ ] Apply the `Header` component in all pages

**Comment by Frank-Schaeske** [comment]
LGTM
