### ISSUE TITLE
User Story 3 - List of set goals

### ISSUE THREAD

**Issue by AliaksandraNovikava** [AliaksandraNovikava/AimHigh#3]
## Value proposition

As an user
I want to see a list of set goals
So that I have overview and reminder of my recently established goals.

## Description

<img src="https://user-images.githubusercontent.com/132850354/251429647-a524b337-5352-4430-9e67-064c01bcf905.jpeg" width="300">

## Acceptance criteria

- [ ] A headline "My goals" is displayed 
- [ ] Previews of all set goals are displayed as a list
- [ ] A goal's icon is displayed in each preview
- [ ] A goal's title is displayed in each preview
- [ ] A creation date is displayed on each preview

## Tasks

- [ ] Create the component `NewGoalPreview` to render a preview of a new goal
- [ ] Style the preview
- [ ] Create the component `NewGoalsList` to render a list of all previews
- [ ] Style the list

**Comment by ghost** [comment]
lgtm 👍
