### ISSUE TITLE
User Story 4 - Separate Pages und Navigation

### ISSUE THREAD

**Issue by AliaksandraNovikava** [AliaksandraNovikava/AimHigh#4]
## Value proposition

As an user
I want to be able to switch between different pages
So that I can navigate the app better and have a clear distinction between goals that I have committed to and other goals suggestions.

## Description

<img src="https://user-images.githubusercontent.com/132850354/251472609-78f16287-2a9a-43ef-a1b4-d57a66426e03.jpeg" width="450">

## Acceptance criteria

- [ ] A navigation link labeled "Add" is displayed
- [ ] A navigation link labeled "My Goals" is displayed
- [ ] Clicking "Add" shows the list of proposed goals and a "set your own goal" button
- [ ] Clicking "My Goals" shows the list of my set goals

## Tasks

- [ ] Adapt the page `pages/index`: rename the function to `ProposedGoalsListPage` and have it render the `ProposedGoalsList` and the `Button` components
- [ ] Create the page `pages/my-goals/index` that renders the `NewGoalsList` component
- [ ] Create the component `Navigation` that renders all navigation links
- [ ] Apply the `Navigation` component in all pages

**Comment by josch87** [comment]
Looks very good to me!
