### ISSUE TITLE
User Story 5 - Mark goals as achieved and list them on a different page

### ISSUE THREAD

**Issue by AliaksandraNovikava** [AliaksandraNovikava/AimHigh#7]
## Value proposition

As an user
I want to be able to mark my set goals as achieved and see them in a list on a different page
So that I have a sense of accomplishment and have a clear distinction between set and achieved goals.

## Description

<img src="https://user-images.githubusercontent.com/132850354/252292169-fecad32a-1578-484f-8174-1b2390550583.jpeg" width="600">

## Acceptance criteria

- [ ] A check-button is displayed on each preview in the "My goals" list
- [ ] Clicking the check-button saves the goal as "checked" and removes its preview from the "My goals" list
- [ ] A navigation link labeled "Achievements" is displayed
- [ ] Clicking the "Achievements" shows a list of as "checked" marked (achieved) goals
- [ ] A headline "My Achievements" is displayed
- [ ] Previews of all achieved goals are displayed as a list
- [ ] A check-button is displayed on each preview

## Tasks

- [ ] Add check-button to the `NewGoalPreview` component
- [ ] Create the component `AchievementsList` to render a list of as "checked" marked goals previews
- [ ] Style the list
- [ ] Create the page `pages/achievements/index` that renders the `AchievementsList` component

**Comment by DErdmann1** [comment]
Great list of acceptance criteria! Like it :)
